export const datas = [
    { id: 1, name: "Thermodynamics", category: "Physics" },
    { id: 2, name: "Quantum Mechanics", category: "Physics" },
    { id: 3, name: "Electromagnetism", category: "Physics" },
    { id: 4, name: "Classical Mechanics", category: "Physics" },
    { id: 5, name: "Nuclear Physics", category: "Physics" },
    { id: 6, name: "Relativity", category: "Physics" },
    { id: 7, name: "Optics", category: "Physics" },
    { id: 8, name: "Fluid Mechanics", category: "Physics" },
    { id: 9, name: "Waves and Oscillations", category: "Physics" },
    { id: 10, name: "Solid State Physics", category: "Physics" },
    { id: 11, name: "Organic Chemistry", category: "Chemistry" },
    { id: 12, name: "Inorganic Chemistry", category: "Chemistry" },
    { id: 13, name: "Physical Chemistry", category: "Chemistry" },
    { id: 14, name: "Analytical Chemistry", category: "Chemistry" },
    { id: 15, name: "Biochemistry", category: "Chemistry" },
    { id: 16, name: "Polymer Chemistry", category: "Chemistry" },
    { id: 17, name: "Medicinal Chemistry", category: "Chemistry" },
    { id: 18, name: "Environmental Chemistry", category: "Chemistry" },
    { id: 19, name: "Chemical Kinetics", category: "Chemistry" },
    { id: 20, name: "Atomic Structure", category: "Chemistry" },
    { id: 21, name: "Genetics", category: "Biology" },
    { id: 22, name: "Cell Biology", category: "Biology" },
    { id: 23, name: "Human Physiology", category: "Biology" },
    { id: 24, name: "Plant Physiology", category: "Biology" },
    { id: 25, name: "Evolution", category: "Biology" },
    { id: 26, name: "Molecular Biology", category: "Biology" },
    { id: 27, name: "Microbiology", category: "Biology" },
    { id: 28, name: "Ecology", category: "Biology" },
    { id: 29, name: "Immunology", category: "Biology" },
    { id: 30, name: "Neurobiology", category: "Biology" },
    { id: 31, name: "Calculus", category: "Mathematics" },
    { id: 32, name: "Algebra", category: "Mathematics" },
    { id: 33, name: "Trigonometry", category: "Mathematics" },
    { id: 34, name: "Linear Algebra", category: "Mathematics" },
    { id: 35, name: "Probability", category: "Mathematics" },
    { id: 36, name: "Statistics", category: "Mathematics" },
    { id: 37, name: "Number Theory", category: "Mathematics" },
    { id: 38, name: "Differential Equations", category: "Mathematics" },
    { id: 39, name: "Discrete Mathematics", category: "Mathematics" },
    { id: 40, name: "Complex Numbers", category: "Mathematics" },
    { id: 41, name: "Data Structures", category: "Computer Science" },
    { id: 42, name: "Algorithms", category: "Computer Science" },
    { id: 43, name: "Databases", category: "Computer Science" },
    { id: 44, name: "Operating Systems", category: "Computer Science" },
    { id: 45, name: "Computer Networks", category: "Computer Science" },
    { id: 46, name: "Artificial Intelligence", category: "Computer Science" },
    { id: 47, name: "Machine Learning", category: "Computer Science" },
    { id: 48, name: "Web Development", category: "Computer Science" },
    { id: 49, name: "Cyber Security", category: "Computer Science" },
    { id: 50, name: "Cloud Computing", category: "Computer Science" },
    { id: 51, name: "Renewable Energy", category: "Environmental Science" },
    { id: 52, name: "Waste Management", category: "Environmental Science" },
    { id: 53, name: "Climate Change", category: "Environmental Science" },
    { id: 54, name: "Water Resources", category: "Environmental Science" },
    { id: 55, name: "Pollution Control", category: "Environmental Science" },
    { id: 56, name: "Biodiversity", category: "Environmental Science" },
    { id: 57, name: "Sustainable Development", category: "Environmental Science" },
    { id: 58, name: "Environmental Laws", category: "Environmental Science" },
    { id: 59, name: "Green Technology", category: "Environmental Science" },
    { id: 60, name: "Ecosystem Analysis", category: "Environmental Science" },
    { id: 61, name: "Electrical Circuits", category: "Engineering" },
    { id: 62, name: "Digital Electronics", category: "Engineering" },
    { id: 63, name: "Control Systems", category: "Engineering" },
    { id: 64, name: "Fluid Dynamics", category: "Engineering" },
    { id: 65, name: "Structural Analysis", category: "Engineering" },
    { id: 66, name: "Engineering Mechanics", category: "Engineering" },
    { id: 67, name: "Thermal Engineering", category: "Engineering" },
    { id: 68, name: "Mechatronics", category: "Engineering" },
    { id: 69, name: "Instrumentation", category: "Engineering" },
    { id: 70, name: "Production Engineering", category: "Engineering" },
    { id: 71, name: "Digital Logic Design", category: "Computer Science" },
    { id: 72, name: "Compiler Design", category: "Computer Science" },
    { id: 73, name: "Software Engineering", category: "Computer Science" },
    { id: 74, name: "Parallel Computing", category: "Computer Science" },
    { id: 75, name: "Embedded Systems", category: "Computer Science" },
    { id: 76, name: "Cloud Architecture", category: "Computer Science" },
    { id: 77, name: "Ethical Hacking", category: "Computer Science" },
    { id: 78, name: "Mobile App Development", category: "Computer Science" },
    { id: 79, name: "Natural Language Processing", category: "Computer Science" },
    { id: 80, name: "Computer Graphics", category: "Computer Science" },
    { id: 81, name: "Set Theory", category: "Mathematics" },
    { id: 82, name: "Graph Theory", category: "Mathematics" },
    { id: 83, name: "Topology", category: "Mathematics" },
    { id: 84, name: "Mathematical Modeling", category: "Mathematics" },
    { id: 85, name: "Real Analysis", category: "Mathematics" },
    { id: 86, name: "Vector Calculus", category: "Mathematics" },
    { id: 87, name: "Combinatorics", category: "Mathematics" },
    { id: 88, name: "Geometry", category: "Mathematics" },
    { id: 89, name: "Matrix Algebra", category: "Mathematics" },
    { id: 90, name: "Logarithms", category: "Mathematics" },
    { id: 91, name: "Reproductive Biology", category: "Biology" },
    { id: 92, name: "Biostatistics", category: "Biology" },
    { id: 93, name: "Pathology", category: "Biology" },
    { id: 94, name: "Forensic Biology", category: "Biology" },
    { id: 95, name: "Developmental Biology", category: "Biology" },
    { id: 96, name: "Enzymology", category: "Biology" },
    { id: 97, name: "Zoology", category: "Biology" },
    { id: 98, name: "Botany", category: "Biology" },
    { id: 99, name: "Marine Biology", category: "Biology" },
    { id: 100, name: "Pharmacology", category: "Biology" }
  ];
  